//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSDLab_Project.Models
{
    using System;
    using System.Collections.Generic;

    public partial class TransactionHeader
    {
        public TransactionHeader() // Constructor
        {
            this.TransactionDetails = new HashSet<TransactionDetail>();
        }

        public int TransactionID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string PaymentMethod { get; set; }
        public string Status { get; set; } // It is 'Status'

        // It IS 'TransactionDetails'
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
        public virtual User User { get; set; }
    }
}